# Copyright 2023-present the International Business Machines.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# The nine prompts of the generation pipeline, verbatim from Phase 1 Appendix A.
#
# P1-P5 generate; V1-V4 validate. V5 is not a prompt -- it is the committee protocol
# that runs V1/V2/V4 (see `validate.py`).
#
# These strings are the SPEC, not a paraphrase of it: the Phase-1 document and this
# module are each other's reference, and `tests/test_locobench_harness.py` asserts the
# instruction count and placeholder set of every one against PROMPT_SPEC below. If the
# two ever diverge, the corpus would be generated by prompts no document describes,
# and that failure is silent -- hence the test.
#
# Placeholders are `[NAME_PLACEHOLDER]` (LoReFact's convention, kept for lineage)
# rather than Mellea's `{{var}}`, because these prompts are filled by `fill()` here
# rather than by `user_variables`: several carry literal JSON braces that Mellea's
# templating would try to interpret.

from __future__ import annotations

import re

# --- P1: topic to question -----------------------------------------
PROMPT_P1 = r"""
Instructions:
1. You are given a TOPIC. Generate one open-ended QUESTION about that topic.
2. The QUESTION must begin with Why, How, What, Does, or Which.
3. The QUESTION must elicit an answer containing MULTIPLE, DIVERSE logical
   relationships. Aim for an answer that would naturally contain at least four
   of the following: a causal chain; a condition; a temporal ordering; an
   evidential appeal; a general claim with a specific instance; a restatement
   or definitional equivalence; a non-exhaustive contrast; an EXHAUSTIVE pair
   of competing alternatives of which EXACTLY ONE can hold; a disjunctive pair
   of which AT LEAST ONE must hold; a tension that an authoritative finding
   later resolves.
4. Prefer topics where competing explanations are adjudicated: incident
   investigations, litigation, diagnostic reasoning, attribution disputes,
   competing scientific hypotheses. Such topics naturally produce exhaustive
   alternatives and resolving holdings.
5. The QUESTION must be answerable in 500-900 words of formal prose.
6. The QUESTION must not itself contain the words "cause", "condition",
   "alternative", or "contrast", so the answer's relations are not primed
   lexically.
7. Do NOT ask a multi-part question joined by "and" - one question only.
8. Wrap the QUESTION in square brackets.
9. Output the bracketed QUESTION only, with no preamble.

Use the following examples to better understand your task.

TOPIC: aviation component failure investigation
QUESTION: [How do investigators determine responsibility when a component
supplied by a third party fails in service and the operator and the
manufacturer offer competing explanations?]

TOPIC: antibiotic resistance in hospital settings
QUESTION: [Why does resistance emerge in some hospital units but not others,
and how is a specific outbreak traced to its origin?]

Your Task:
TOPIC: [TOPIC_PLACEHOLDER]
QUESTION:
"""

# --- P2: atomic claim generation -----------------------------------
PROMPT_P2 = r"""
Instructions:
1. You are given a QUESTION. Generate a set of ATOMIC CLAIMS that a
   well-informed answer to it might contain.
2. An atomic claim is a sentence containing a singular piece of information,
   which should be basic, indivisible, and independently verifiable.
3. Generate exactly 24 atomic claims, in the following required composition:
   (a) 14 factually correct claims;
   (b) 4 factually incorrect claims (plausible but false);
   (c) 2 EXHAUSTIVE ALTERNATIVE claims: a pair X, Y such that exactly one of X
       and Y must be true - they cannot both hold, and they cannot both fail.
       Example pair: "No one was harmed in the incident." / "Three people died
       in the incident."
   (d) 2 DISJUNCTIVE claims: a pair X, Y such that at least one must be true,
       but both may be true simultaneously. Make each one a STATE OF THE WORLD,
       not a finding or a check that reported something: "the alloy was
       substituted" and "the batch was mislabelled", not "assay A flagged it"
       and "assay B flagged it".
   (e) 2 EQUIVALENT claims: a pair X, Y asserting the same fact in different
       words, so that either one being true makes the other true.
4. Additionally generate 2 HOLDING claims: sentences in which an authority
   (a court, tribunal, regulator, final report, or review board) reaches a
   determination that settles a dispute between two other claims in your list.
   A holding claim must use adjudicating language - "held", "ruled",
   "concluded", "determined", "found that", "ultimately".
5. Each claim must be a single declarative sentence with no connective linking
   it to another claim. Do NOT use "because", "although", "therefore", "if",
   "while", "however". Relations are added at a later stage, not here.
6. Do NOT indicate which claims are factually incorrect in their wording; do
   NOT hedge with "assume", "might", "possibly", or "allegedly".
7. Output as a markdown code block: an unordered list with "-" bullets. Append
   a tag in square brackets to every claim, one of: [correct], [incorrect],
   [alt-pair-1], [alt-pair-2], [disj-pair-1], [disj-pair-2], [equiv-pair-1],
   [equiv-pair-2], [holding].

Use the following example to better understand your task.

QUESTION: [How do investigators determine responsibility when a component
supplied by a third party fails in service and the operator and the
manufacturer offer competing explanations?]

ATOMIC CLAIMS:
```
- AeroParts supplied turbine blades to the carrier. [correct]
- The turbine blades were installed in the carrier's A-320 fleet. [correct]
- Seventeen turbine blades failed in flight during service. [correct]
- The regulator opened a safety probe into the blade failures. [correct]
- Maintenance logs recorded abnormal vibration on the failed blades. [correct]
- The airline argued that the failures were caused by pilot error. [correct]
- The final report concluded the root cause was a metallurgical defect. [correct]
- The regulator issued an order grounding the fleet. [correct]
- Every affected aircraft was pulled from service. [equiv-pair-1]
- The regulator's order removed all affected aircraft from operation. [equiv-pair-2]
- The blades were certified under a 1998 airworthiness standard. [incorrect]
- No one was harmed in the incidents. [alt-pair-1]
- Three passengers died in one of the failures. [alt-pair-2]
- The alloy supplied for the blades was substituted. [disj-pair-1]
- The blade batch was mislabelled at the mill. [disj-pair-2]
- The tribunal held that AeroParts was liable for the blade failures. [holding]
- The accident report found the pilots not at fault. [holding]
```

Your Task:
QUESTION: [QUESTION_PLACEHOLDER]
ATOMIC CLAIMS:
"""

# --- P3: relation plan generation ----------------------------------
PROMPT_P3 = r"""
Instructions:
1. You are given a QUESTION and a tagged list of ATOMIC CLAIMS. Produce a
   RELATION PLAN: a machine-readable graph of the logical relations a response
   should draw between those claims.
2. Select 14-16 claims to use. Aim for 15. Number them with FRESH consecutive
   positions: the first claim you assert is pos 1, the next pos 2, and so on
   with NO gaps and NO repeats, ending at pos N where N is how many you
   selected. Do NOT carry over the numbering of the input list - if you pick the
   3rd, 7th and 12th claims they become pos 1, 2 and 3. The position is the
   order the response will assert the claim in. Every selected claim keeps its
   text EXACTLY as given. Do NOT introduce information not in the claims, and
   do NOT alter the claims.
3. Plan EXACTLY 10 RELATIONS. Each relation connects exactly two selected claims
   and has a SENSE. Every relation must join a DIFFERENT pair of claims: once two
   claims are related, that pair is used up and must not appear again in the
   relations list, in either direction. The SENSE is one of: Cause-Effect,
   Effect-Cause, Evidence, Condition,
   Restatement, Instantiation, Contrast, Concession, Alternative, Disjunction,
   Precedence, Succession.
   - Cause-Effect: source causes target. Effect-Cause: source is the effect,
     target its cause.
   - Evidence: source is evidence for target. Condition: source is a condition
     for target.
   - Restatement: source and target assert the same thing.
   - Instantiation: source is a general claim, target a specific instance.
   - Contrast: opposition that is NOT exhaustive - both could be false.
   - Concession: a tension the text itself resolves.
   - Alternative: EXHAUSTIVE competing options - EXACTLY ONE holds. Not both,
     and not neither. Use your [alt-pair-*] claims here.
   - Disjunction: AT LEAST ONE holds; both may hold. Use your [disj-pair-*]
     claims here.
   - Precedence / Succession: ordered in time with NO truth dependence -
     neither claim being true or false says anything about the other.
4. Keep relations LOCAL: prefer pairs within 4 POSITIONS of each other, so the
   graph stays recoverable from the response by a local reader. A longer-range
   pair is acceptable when the two claim texts share a named entity, and a few
   long-range links (for instance a closing claim answering the opening one) are
   fine. Order the positions so that related claims sit near each other.
5. The plan must include AT LEAST ONE relation of each of these senses:
   Alternative, Disjunction, Restatement, Concession, and one of
   Precedence/Succession.
6. Every Concession must be marked resolved or unresolved. A resolved
   Concession must name a RESOLVER: a [holding] claim, also selected and
   positioned AFTER both endpoints.
7. Give each relation an intended STRENGTH BAND: strong (0.85-1.00), moderate
   (0.60-0.84), or weak (0.35-0.59) - how strongly the source determines the
   target under that sense. Restatement relations are always strong.
8. Give each relation an intended VALIDITY: valid if the relation genuinely
   holds between the claims as stated; invalid if it does not. Of your 10
   relations, mark EXACTLY 6 "valid" and EXACTLY 4 "invalid" - count them before
   you emit, and do not compute a percentage. For each invalid relation give an
   ERROR_KIND, one of: wrong_sense, wrong_direction, false_endpoint, spurious.
9. Also list 4-6 NON-RELATIONS (aim for 5): pairs of selected claims within 4
   positions of each other between which the response must draw NO logical
   dependence. These are the distractors a relation miner must correctly label
   None. A non-relation pair must NOT also appear in your relations list, in
   either direction - the two lists are disjoint.
10. Output a single JSON object in a code block and nothing else. Below is a
    COMPLETE, correctly-shaped example - copy its structure exactly, not its
    text. It has 14 atoms numbered 1..14 with no gaps, 10 relations (6 valid, 4
    invalid), all five required senses, and 5 non-relations disjoint from the
    relations:

```json
{
  "atoms": [
    {"pos": 1, "text": "<claim text>"}, {"pos": 2, "text": "<claim text>"},
    {"pos": 3, "text": "<claim text>"}, {"pos": 4, "text": "<claim text>"},
    {"pos": 5, "text": "<claim text>"}, {"pos": 6, "text": "<claim text>"},
    {"pos": 7, "text": "<claim text>"}, {"pos": 8, "text": "<claim text>"},
    {"pos": 9, "text": "<claim text>"}, {"pos": 10, "text": "<claim text>"},
    {"pos": 11, "text": "<claim text>"}, {"pos": 12, "text": "<claim text>"},
    {"pos": 13, "text": "<claim text>"}, {"pos": 14, "text": "<claim text>"}
  ],
  "relations": [
    {"source_pos": 1, "target_pos": 2, "sense": "Cause-Effect",
     "strength_band": "strong", "validity": "valid",
     "error_kind": null, "resolved": null, "resolver_pos": null},
    {"source_pos": 2, "target_pos": 3, "sense": "Evidence",
     "strength_band": "moderate", "validity": "valid",
     "error_kind": null, "resolved": null, "resolver_pos": null},
    {"source_pos": 3, "target_pos": 4, "sense": "Restatement",
     "strength_band": "strong", "validity": "valid",
     "error_kind": null, "resolved": null, "resolver_pos": null},
    {"source_pos": 5, "target_pos": 6, "sense": "Alternative",
     "strength_band": "strong", "validity": "valid",
     "error_kind": null, "resolved": null, "resolver_pos": null},
    {"source_pos": 7, "target_pos": 8, "sense": "Disjunction",
     "strength_band": "moderate", "validity": "valid",
     "error_kind": null, "resolved": null, "resolver_pos": null},
    {"source_pos": 9, "target_pos": 10, "sense": "Concession",
     "strength_band": "moderate", "validity": "valid",
     "error_kind": null, "resolved": true, "resolver_pos": 11},
    {"source_pos": 11, "target_pos": 12, "sense": "Precedence",
     "strength_band": "weak", "validity": "invalid",
     "error_kind": "wrong_sense", "resolved": null, "resolver_pos": null},
    {"source_pos": 12, "target_pos": 13, "sense": "Cause-Effect",
     "strength_band": "moderate", "validity": "invalid",
     "error_kind": "wrong_direction", "resolved": null, "resolver_pos": null},
    {"source_pos": 13, "target_pos": 14, "sense": "Contrast",
     "strength_band": "weak", "validity": "invalid",
     "error_kind": "spurious", "resolved": null, "resolver_pos": null},
    {"source_pos": 4, "target_pos": 6, "sense": "Instantiation",
     "strength_band": "weak", "validity": "invalid",
     "error_kind": "false_endpoint", "resolved": null, "resolver_pos": null}
  ],
  "non_relations": [
    {"source_pos": 1, "target_pos": 4}, {"source_pos": 2, "target_pos": 5},
    {"source_pos": 6, "target_pos": 9}, {"source_pos": 8, "target_pos": 11},
    {"source_pos": 10, "target_pos": 13}
  ]
}
```

Your Task:
QUESTION: [QUESTION_PLACEHOLDER]
ATOMIC CLAIMS: [CLAIMS_PLACEHOLDER]
RELATION PLAN:
"""

# --- P4: response generation ---------------------------------------
PROMPT_P4 = r"""
Instructions:
1. You are given a QUESTION and a RELATION PLAN in JSON. Write a RESPONSE that
   answers the question and realizes the plan exactly.
2. Assert every planned atom EXACTLY ONCE, in the plan's POSITION order,
   preserving each atom's factual content. Do not restate an atom you have
   already asserted in order to attach a later relation to it - refer back with
   a pronoun or a short noun phrase instead. Name that phrase after the thing
   the atom is about, not after its status as a finding: "the primitive carpal
   morphology" or "that wrist evidence", not "the analysis's flagging of
   primitive traits"; "these two accounts" or "either possibility", not "the two
   claims in circulation". A summary phrase covering both endpoints of one
   connective is fine - "at least one of these must hold: X, or Y". You may
   adjust surface wording for fluency but must not change what is asserted.
   Quantifiers, determiners, numbers, dates, polarity and modals are CONTENT,
   not wording: keep "all", "only", "no", "some", "each", "never" and every
   figure exactly as the atom has them. "All tools were crafted by a single
   culture" may become "every one of the tools came from a single culture", but
   never "the tools were crafted by a single culture" - dropping "All" weakens
   the claim and counts as changing it.
   Never let one atom absorb another: each must stay separately true or false.
   Joining two atoms with a connective is fine and often required - "either X or
   Y" and "although X, Y" both assert two atoms and are exactly what instruction
   3 asks for.
3. Realize every planned RELATION so a careful reader could recover it from the
   text alone, using language appropriate to its sense:
   - Cause-Effect / Effect-Cause: "caused", "led to", "resulted from", "because"
   - Evidence: "indicates", "confirms", "as shown by"
   - Condition: "if", "provided that", "only when"
   - Restatement: "that is", "in other words", "equivalently"
   - Instantiation: "for example", "specifically", "in one case"
   - Contrast: "by contrast", "whereas", "on the other hand"
   - Concession: "although", "despite", "even though"
   - Alternative: make the exhaustiveness EXPLICIT - "either ... or", "one of
     these accounts must be wrong", "the two cannot both be true, and one of
     them must hold"
   - Disjunction: make the at-least-one reading EXPLICIT - "at least one of",
     "one or both", "perhaps both". Say "perhaps both", never "possibly both".
     A bare "X, or Y" is NOT enough for either of these two senses: on its own it
     leaves a reader unable to tell whether both claims could hold, which is the
     only thing separating Alternative from Disjunction. Every such pair needs its
     marker - "either X or Y" when exactly one holds, "at least one of X or Y,
     perhaps both" when both may.
   - Precedence / Succession: state the sequence EXPLICITLY in one sentence
     joining both claims - "before", "after", "subsequently", "earlier than",
     "which postdates" - while keeping the ordering purely chronological, so a
     reader sees only when things happened and infers nothing from it. Write
     "X, which predates Y" or "Y came after X", not "X and therefore Y".
     Asserting the two claims in separate sentences leaves this relation
     unrealized: an ordering a reader cannot see is the same as no ordering.
4. For each planned NON-RELATION, assert both atoms but draw no dependence
   between them. Separate them by DISTANCE and PARAGRAPHING, not by a marker:
   put other material between them, or place them in different paragraphs, and
   simply use no connective. Do NOT announce the absence of a link - phrases
   like "In an unrelated matter", "Separately", or "On a different note" read as
   stitched-together annotation rather than prose and will be marked down.
5. For a resolved Concession, assert the resolver atom after both endpoints and
   present it as settling the tension.
6. Write it as a continuous expository answer to the QUESTION - an argument a
   domain expert would publish, organized into 3-5 paragraphs, in which the
   planned relations are simply how the argument hangs together. Do NOT walk the
   plan relation by relation: a reader must not be able to tell that a plan
   exists. Restate a subject to carry an argument forward ("the radiocarbon
   date", "that attribution"), never the earlier sentence as a step ("the
   finding just reported", "the provision just stated", "the ordering just
   described"). Use precise and formal language, avoiding vague generalizations
   and rhetorical fillers. Aim for 550-650 words. The 500-word floor is a hard
   requirement checked by an automated reader, which rejects a shorter answer
   outright however good it is, so give each atom and each relation the space to
   be argued rather than compressing them into a summary.
7. Do NOT mention the relation plan, the senses, the strength bands, the
   validity labels, or the fact that some content is incorrect. Do NOT hedge
   with "assume", "might", "possibly", "allegedly", "supposedly",
   "reportedly", or "it is claimed" around planned-invalid relations - assert
   them in the same register as the valid ones. Do NOT add headings, bullet
   lists, or annotations.
8. Wrap the RESPONSE in a code block whose contents are the prose itself, as you
   would publish it. The block holds the answer, not a JSON object or any other
   payload with the prose inside a field.

Your Task:
QUESTION: [QUESTION_PLACEHOLDER]
RELATION PLAN: [PLAN_PLACEHOLDER]
RESPONSE:
"""

# --- P5: parameterized perturbation --------------------------------
PROMPT_P5 = r"""
Instructions:
1. You are given a RESPONSE, its RELATION PLAN, and one PERTURBATION to apply.
2. Apply ONLY the named perturbation. Change the minimum number of words
   needed. Every other relation, atom, and sentence must be preserved verbatim.
3. The perturbations are defined as follows.
   - wrong_sense(edge, new_sense): rewrite the connective realizing that edge so
     the text draws new_sense instead. Keep both atoms' content unchanged.
   - direction_reversal(edge): rewrite so the relation runs from the target to
     the source. Keep both atoms' content unchanged.
   - exhaustiveness_flip(edge): if the edge is Alternative, rewrite so the two
     claims merely oppose without being exhaustive (both could be false). If it
     is Contrast, rewrite so exactly one must hold.
   - remove_resolution(edge): delete the resolver sentence and any reference to
     it, leaving the conceded tension unresolved. Change nothing else.
   - inject_contradiction(atom): add ONE new sentence asserting a claim that
     directly contradicts the named atom. Place it at least two sentences later.
   - break_chain(edge): remove or negate the link realizing that edge so the
     causal chain no longer connects, keeping both endpoint atoms present.
   - shuffle_order(level): reorder the response's sentences without changing any
     wording. level=full permutes all sentences; level=block permutes paragraph
     blocks; level=adjacent swaps one adjacent pair.
   - spurious_relation(atom_a, atom_b): add a connective asserting a causal or
     contradictory link between two atoms the original response kept separate.
     Add no new factual content.
   - drop_relation(edge): remove the connective realizing that edge so the two
     atoms are merely adjacent assertions. Keep both atoms.
   - ordering_only(edge): rewrite a Precedence edge as Succession, or the
     reverse, preserving the actual chronology and adding NO causal or
     inferential language. The truth of neither atom may become dependent on
     the other.
4. Do not change the response's length by more than 15 percent, except for
   inject_contradiction (which adds one sentence) and remove_resolution /
   break_chain (which remove one).
5. Output the perturbed RESPONSE in a code block, then a second code block
   containing a JSON diff:
   {"operator": "...", "target": ..., "sentences_changed": [...],
    "relations_added": [...], "relations_removed": [...],
    "relations_relabeled": [...]}

Your Task:
RESPONSE: [RESPONSE_PLACEHOLDER]
RELATION PLAN: [PLAN_PLACEHOLDER]
PERTURBATION: [OPERATOR_PLACEHOLDER]
"""

# --- V1: round-trip relation recovery ------------------------------
PROMPT_V1 = r"""
Let's define a function named recover_relations(response: str,
atoms: dict[str, str]).
Given a RESPONSE and the ATOMS drawn from it, the function returns the
list of logical relations the response ITSELF draws between those atoms.

ATOMS maps an atom's NUMBER to its text, numbered from 1. Use those numbers, as
integers, to identify atoms in your output: if the relation holds between the
atoms numbered "3" and "7", emit source 3 and target 7. Never renumber them and
never count from zero.

For each ORDERED pair (i, j) that the response actually relates, emit one object:
  {"source": i, "target": j,
   "sense": one of ["Cause-Effect","Effect-Cause","Evidence","Condition",
     "Restatement","Instantiation","Contrast","Concession","Alternative",
     "Disjunction","Precedence","Succession"],
   "coupling": one of ["entailment","contradiction","equivalence","exclusive",
     "co_necessity","none"],
   "strength_band": one of ["strong","moderate","weak"],
   "resolved": true or false or null}

Rules:
- Emit a relation ONLY if the response itself draws that connection, as written
  or as a clear step in the author's argument. Do not emit a relation that is
  merely plausible in general.
- Pick the MOST SPECIFIC sense the text supports, never the most general one.
  Five senses compile to "entailment", and "Evidence" is the broadest of them,
  so it is the easy wrong answer: use it only for evidential support ("indicates",
  "confirms", "as shown by", "suggests"). Prefer "Cause-Effect" when the text says
  one thing brought the other about ("caused", "led to", "resulted in",
  "because"), "Effect-Cause" when that runs the other way ("resulted from",
  "is explained by"), "Condition" for "if", "provided that", "only when", and
  "Instantiation" when one claim is an INSTANCE of the other, i.e. a specific
  case of a general statement ("for example", "specifically", "such as").
- Use "Alternative" only when the two claims cannot both be true AND cannot both
  be false. Use "Contrast" when they merely cannot both be true - look for "by
  contrast", "whereas", "on the other hand", or two claims set against each other
  without either being conceded.
- Use "Concession" when the text grants a tension and then overrides it -
  "although", "despite", "even though", "notwithstanding", or a clause that admits
  one claim while asserting the other anyway. A concessive marker attaching two
  claims IS a relation between them, even when the concession sits in a
  subordinate clause rather than its own sentence.
- Use "Disjunction" only when the response rules out both claims being false
  ("at least one of", "one or both", "perhaps both").
- Use "Precedence" or "Succession" only when the ordering carries no truth
  dependence; set their coupling to "none". These ARE relations and must be
  emitted: "before", "after", "subsequently", "earlier", "later", or an explicit
  statement that a sequence carries no causal or inferential force. Read such a
  pair as "Precedence" when the source comes first in time and "Succession" when
  it comes second. Do not silently upgrade one to "Cause-Effect" or "Evidence"
  because the two events sit next to each other in an argument.
- Relate a pair only ONCE unless the response genuinely draws two different
  connections between them. Emitting many relations does not make the recovery
  more complete; a pair the response merely mentions in the same paragraph is not
  related.
- "coupling" is not an independent choice: it must be the coupling that the
  "sense" you chose compiles to. Cause-Effect, Effect-Cause, Evidence,
  Condition and Instantiation are "entailment"; Restatement is "equivalence";
  Contrast and Concession are "contradiction"; Alternative is "exclusive";
  Disjunction is "co_necessity"; Precedence and Succession are "none".
- Pairs the response leaves unrelated must be omitted entirely.

The function returns a JSON list. Note that your response will be passed to the
python interpreter, SO NO OTHER WORDS!

recover_relations(response="[RESPONSE_PLACEHOLDER]", atoms=[ATOMS_PLACEHOLDER])
"""

# --- V2: exhaustiveness adjudication -------------------------------
PROMPT_V2 = r"""
Let's define a function named adjudicate_exhaustiveness(claim_a: str,
claim_b: str, response: str).

Given two claims and the response that asserts both, the function decides the
logical relationship between their truth values, returning exactly one of:
  "A" - EXHAUSTIVE EXCLUSION: exactly one of A and B holds. They cannot both be
        true, and they cannot both be false.
  "B" - NON-EXHAUSTIVE OPPOSITION: they cannot both be true, but both could be
        false (some third possibility exists).
  "C" - DISJUNCTION: at least one holds, and both may hold together.
  "D" - NEITHER: the truth values are not coupled in any of these ways.

To decide between A and B, ask: is there a coherent third state of the world in
which A and B are BOTH false? If yes, answer B. If no such third state exists,
answer A.
To decide between A and C, ask: could A and B both be true at once? If yes,
answer C.

Answer with the single letter only. Note that your response will be passed to
the python interpreter, SO NO OTHER WORDS!

adjudicate_exhaustiveness(claim_a="[CLAIM_A_PLACEHOLDER]",
                          claim_b="[CLAIM_B_PLACEHOLDER]",
                          response="[RESPONSE_PLACEHOLDER]")
"""

# --- V3: naturalness and leakage audit -----------------------------
PROMPT_V3 = r"""
Let's define a function named check_response(response: str).
The function audits a generated response and returns a JSON object:
  {"fluency": 1-5, "formality": 1-5, "organization": 1-5,
   "leakage": [list of quoted spans], "hedging": [list of quoted spans],
   "artifacts": [list of quoted spans]}

- fluency, formality, organization: 5 = indistinguishable from expert human
  prose; 1 = badly degraded.
- leakage: any span revealing the response was generated from an annotation
  plan. Read this NARROWLY: naming a relation type or sense; naming the plan,
  the strength bands, or the validity labels; referring to "claims", "atoms" or
  "statements" as the objects the text was assembled from; or any label, tag,
  numeric index, or bracketed marker. Do NOT flag a connective or coordination
  that merely realizes a relation - "either X or Y", "at least one of X or Y",
  "at least one of these was true", "perhaps both",
  "the two cannot both be true, and one of them must hold", "although X, Y",
  "before", "after", "as indicated by", "as shown by", "which indicates", or an
  explicit statement that an ordering carries no causal or inferential force. A
  writer is REQUIRED to use those, and a coupling over two claims' joint truth
  cannot be expressed without one. Every span you report must be QUOTED VERBATIM
  from the response; if you cannot copy it out of the text, it is not there and
  must not be reported. Do NOT
  flag ordinary scholarly vocabulary used about the subject matter, such as
  "claim", "outcome", "reading", "account" or "finding".
- hedging: a span using one of these EXACT words: "assume", "might",
  "possibly", "allegedly", "supposedly", "reportedly", "it is claimed". The list
  is CLOSED - quote the word you found, and flag nothing that does not contain
  one of them. Uncertainty a writer is REQUIRED to express is not hedging: "at
  least one of X or Y, perhaps both" and "either X or Y" state the logical
  strength of a relation, not doubt about the content, so do NOT flag them.
- artifacts: enumerated list structure, headings, repeated template phrasing, or
  a sentence that reads as a stitched-together claim rather than prose.

Return the JSON object only. Note that your response will be passed to the
python interpreter, SO NO OTHER WORDS!

check_response(response="[RESPONSE_PLACEHOLDER]")
"""

# --- V4: atom coverage and realized positions ----------------------
PROMPT_V4 = r"""
Let's define a function named check_atom_coverage(response: str,
atoms: list[str]).
For each atom, the function decides whether the response asserts it, returning a
JSON list of objects:
  {"index": i,
   "status": one of ["asserted", "altered", "missing", "merged"],
   "span": the quoted span of the response that asserts it, or null,
   "position": the 1-based index of that span among the response's sentences}

- "asserted": the response asserts the atom's full content, in any wording.
- "altered": the response asserts something related but changes the atom's
  content (a different number, date, entity, or polarity).
- "missing": the response does not assert the atom.
- "merged": the atom's content has been absorbed into another atom's, so it is no
  longer separately assertable - you could not negate this atom alone and leave
  the other standing. Reserve this for genuine loss of content.
  Two atoms joined by a connective are NOT merged: "either X or Y", "at least one
  of X or Y", "although X, Y", "X, whereas Y", and "X; that is, Y" each assert
  BOTH atoms, because each remains independently true or false. Mark both
  "asserted", with the span covering the part that asserts each one.

Return the JSON list only. Note that your response will be passed to the python
interpreter, SO NO OTHER WORDS!

check_atom_coverage(response="[RESPONSE_PLACEHOLDER]", atoms=[ATOMS_PLACEHOLDER])
"""

# ----------------------------------------------------------------------------
# The registry, and the spec the drift test checks against.
# ----------------------------------------------------------------------------

PROMPTS: dict[str, str] = {
    "P1": PROMPT_P1,
    "P2": PROMPT_P2,
    "P3": PROMPT_P3,
    "P4": PROMPT_P4,
    "P5": PROMPT_P5,
    "V1": PROMPT_V1,
    "V2": PROMPT_V2,
    "V3": PROMPT_V3,
    "V4": PROMPT_V4,
}

GENERATION_PROMPTS = ("P1", "P2", "P3", "P4", "P5")
VALIDATION_PROMPTS = ("V1", "V2", "V3", "V4")

# Per prompt: (numbered-instruction count, required placeholders). Transcribed from
# Phase 1 Appendix A; the test asserts the constants above still match. V1-V4 use
# LoReFact's function-call idiom and carry no numbered instructions, which is why their
# count is 0 -- their contract is the signature line instead.
PROMPT_SPEC: dict[str, tuple[int, tuple[str, ...]]] = {
    "P1": (9, ("TOPIC_PLACEHOLDER",)),
    "P2": (7, ("QUESTION_PLACEHOLDER",)),
    "P3": (10, ("CLAIMS_PLACEHOLDER", "QUESTION_PLACEHOLDER")),
    "P4": (8, ("PLAN_PLACEHOLDER", "QUESTION_PLACEHOLDER")),
    "P5": (5, ("OPERATOR_PLACEHOLDER", "PLAN_PLACEHOLDER", "RESPONSE_PLACEHOLDER")),
    "V1": (0, ("ATOMS_PLACEHOLDER", "RESPONSE_PLACEHOLDER")),
    "V2": (0, ("CLAIM_A_PLACEHOLDER", "CLAIM_B_PLACEHOLDER", "RESPONSE_PLACEHOLDER")),
    "V3": (0, ("RESPONSE_PLACEHOLDER",)),
    "V4": (0, ("ATOMS_PLACEHOLDER", "RESPONSE_PLACEHOLDER")),
}

_PLACEHOLDER_RE = re.compile(r"\[([A-Z_]+_PLACEHOLDER)\]")
_INSTRUCTION_RE = re.compile(r"(?m)^\d+\. ")


def placeholders(prompt_id: str) -> tuple[str, ...]:
    """Return the placeholder names a prompt declares, sorted.

    Args:
        prompt_id: One of :data:`PROMPTS`.

    Returns:
        The placeholder names, without brackets.

    Raises:
        KeyError: If the prompt id is unknown.
    """
    return tuple(sorted(set(_PLACEHOLDER_RE.findall(PROMPTS[prompt_id]))))


def instruction_count(prompt_id: str) -> int:
    """Return the number of numbered instructions in a prompt.

    Args:
        prompt_id: One of :data:`PROMPTS`.

    Returns:
        The count. Zero for the function-call-style validators.

    Raises:
        KeyError: If the prompt id is unknown.
    """
    return len(_INSTRUCTION_RE.findall(PROMPTS[prompt_id]))


def fill(prompt_id: str, **values: str) -> str:
    """Substitute a prompt's placeholders.

    Every declared placeholder must be supplied and every supplied value must be
    declared: a typo in either direction would otherwise ship a prompt with a literal
    ``[FOO_PLACEHOLDER]`` in it, which the model would dutifully treat as content.

    Args:
        prompt_id: One of :data:`PROMPTS`.
        **values: One keyword per placeholder, lower-cased and without the
            ``_PLACEHOLDER`` suffix -- e.g. ``topic=`` for ``[TOPIC_PLACEHOLDER]``.

    Returns:
        The filled prompt.

    Raises:
        KeyError: If the prompt id is unknown.
        ValueError: If a declared placeholder is missing or an extra value is given.
    """
    template = PROMPTS[prompt_id]
    declared = {p.removesuffix("_PLACEHOLDER").lower() for p in placeholders(prompt_id)}
    supplied = set(values)
    if declared - supplied:
        raise ValueError(
            f"{prompt_id}: missing value(s) for {sorted(declared - supplied)}."
        )
    if supplied - declared:
        raise ValueError(
            f"{prompt_id}: unexpected value(s) {sorted(supplied - declared)}; "
            f"declared placeholders are {sorted(declared)}."
        )
    out = template
    for key, value in values.items():
        out = out.replace(f"[{key.upper()}_PLACEHOLDER]", str(value))
    return out


__all__ = [
    "GENERATION_PROMPTS",
    "PROMPTS",
    "PROMPT_P1",
    "PROMPT_P2",
    "PROMPT_P3",
    "PROMPT_P4",
    "PROMPT_P5",
    "PROMPT_SPEC",
    "PROMPT_V1",
    "PROMPT_V2",
    "PROMPT_V3",
    "PROMPT_V4",
    "VALIDATION_PROMPTS",
    "fill",
    "instruction_count",
    "placeholders",
]
