#!/usr/bin/env bash
# Render the Response B anatomy figure of the coherence paper to
# docs/iclr2027/coherence/figures/response-b-anatomy.png.
#
# The PNG is a derived artifact: figures/response-b-anatomy.tex is the source of
# truth, and this script renders it through the paper's own preamble.tex, so the
# image cannot drift from the in-paper figure. Rerun it after any edit to the
# figure. Do not hand-edit the PNG.
#
# The caption is suppressed (via \rbnocaption, which the figure honours) so the
# PNG is the graphic alone -- wherever it is reused, the surrounding prose
# supplies the explanation. Dropping the caption also drops its two \refs, so
# nothing here depends on the paper's section numbering.
#
# Usage:  bash scripts/make_response_b_png.sh [--dpi N]
set -euo pipefail

DPI=300
[[ "${1:-}" == "--dpi" ]] && DPI="${2:?--dpi needs a value}"

cd "$(dirname "$0")/../docs/iclr2027/coherence"

for tool in pdflatex pdfcrop pdftoppm; do
  command -v "$tool" >/dev/null || { echo "error: $tool not found on PATH" >&2; exit 1; }
done

WRAP=_response_b_png_wrapper
trap 'rm -f "$WRAP".{tex,pdf,aux,log,out} _response_b_png_crop.pdf' EXIT

cat > "$WRAP.tex" <<'TEXEOF'
% Generated by scripts/make_response_b_png.sh -- do not edit or commit.
\input{preamble.tex}
\usepackage[papersize={7.05in,6.4in},margin=0.28in]{geometry}
\pagestyle{empty}
\newcommand{\rbnocaption}{}   % figure renders without its \caption
\begin{document}
\setcounter{figure}{0}
\input{figures/response-b-anatomy}
\clearpage
\end{document}
TEXEOF

pdflatex -interaction=nonstopmode -halt-on-error "$WRAP.tex" >/dev/null
if grep -q "Reference.*undefined\|Citation.*undefined" "$WRAP.log"; then
  echo "error: unresolved reference in the standalone figure; see $WRAP.log" >&2
  exit 1
fi

pdfcrop --margins 6 "$WRAP.pdf" _response_b_png_crop.pdf >/dev/null
pdftoppm -png -r "$DPI" -singlefile _response_b_png_crop.pdf figures/response-b-anatomy

echo "wrote docs/iclr2027/coherence/figures/response-b-anatomy.png at ${DPI} dpi"
